"""``obsidian-projection`` subscription handler (Slice 1 US8).

Turns ``lithos.task.*`` events into a markdown file at
``vault_path / tasks_file`` that the Obsidian Tasks plugin can query.

**Event vocabulary:** the user story names
``{created,updated,completed,cancelled}``, but the live SSE source
(``LithosEventStream``) only emits
``{created,claimed,released,completed,cancelled}`` — there is no
``updated`` event in the Lithos surface today. We subscribe to all
six so the projection actually sees claim transitions (which is what
D6 needs to decide actionability), plus ``updated`` as a forward-
compatibility no-op should the source ever emit it.

Line shape after US13:

    %% Auto-generated by lithos-loom. Hand edits will be overwritten. ... %%

    Open tasks:
        - [ ] <title> [<prio>] 🆔 lithos:<id> [⛔ lithos:<dep>]... \
            [📅 <date>] [#project/<slug>] [#lithos/<route>]

    Resolved tasks (within resolved_ttl_days):
        - [x] <title> ✅ <date> 🆔 lithos:<id> [#project/<slug>]
        - [-] <title> ❌ <date> 🆔 lithos:<id> [#project/<slug>]

(``[⛔ lithos:<dep>]...`` is zero-or-more — one marker per entry
in ``task.metadata.depends_on``.) Optional markers are emitted
only when they apply (see ``_render_line`` and
``_render_resolved_line``). Resolved lines drop actionability-only
markers (priority, deps, due date, ``#lithos/<route>``) — they are
historical record, not work. The base US8 shape —
``- [ ] <title> 🆔 lithos:<id>`` — is preserved for orphan tasks
with no priority / deps / project / scheduled_for / claim, which
is the most common case during early adoption.

US12 ("dependency-blocked tasks still project") is implicitly
satisfied here: ``include_blocked = True`` is the
``ObsidianSyncConfig`` default (US7) and ``is_human_actionable``
only hides blocked tasks when the operator explicitly opts out
(US8) — so by default a task with ``depends_on`` set still appears,
just decorated with ``⛔`` markers the Tasks plugin uses to
recognise it as blocked.

US13 keeps completed/cancelled lines around for
``resolved_ttl_days`` (default 7, on ``ObsidianSyncConfig`` since
US7) so the operator's "done this week" / "cancelled this week"
Tasks-plugin queries work without polluting the open-task inbox.
A TTL sweep runs at the top of every event handle — cheap dict
walk, no new timer infrastructure; long-quiet daemons get a
single sweep-driven file rewrite on the next event arrival.
Resolved entries are immune to re-evaluation events: stale
claimed/released/updated for an already-resolved task no-op on
the state; only TTL expiry can evict.

Terminal events are gated through ``would_be_actionable`` (same
predicate as ``is_human_actionable`` minus the status check) so
autonomous-route work that was never on the operator's view does
not suddenly appear in "done this week" queries on completion.
Resolution dates anchor on Lithos's canonical ``completed_at``
(falling back to ``event.timestamp`` only if the payload is silent),
so reconnect / replay / restart paths render the same date the
operator would have seen at live receipt.

Restart-recovery: ``LithosEventStream`` accepts
``bootstrap_resolved_window`` (set to ``timedelta(days=resolved_ttl_days)``
by the ``obsidian-sync`` child) and over-fetches recent
completed + cancelled tasks at bootstrap, filters by
``completed_at`` client-side, and publishes each as the
appropriate terminal-event type. Open tasks replay as ``created``;
the in-memory state thus rebuilds naturally on restart — same
idempotency contract as ``RouteRunner._processed_tasks`` — for
both open and resolved entries.

The handler maintains an in-process state dict
``{task_id → _StateEntry}``.

File writes are atomic: write to ``<path>.tmp``, fsync, then
``os.replace`` onto the final path. The .tmp file is cleaned up on
any failure between write and replace so stale temps don't litter
the vault. Content-hash dedup ("only write when content has actually
changed") is US14; meanwhile this handler skips the write entirely
whenever nothing about the in-memory state changed.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import os
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

from lithos_loom.bus import Event
from lithos_loom.config import LoomConfig, RouteConfig
from lithos_loom.lithos_client import Task
from lithos_loom.subscriptions._human_actionable import (
    human_blocking_route_name,
    is_human_actionable,
    would_be_actionable,
)

__all__ = ["make_handler"]

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class _StateEntry:
    """One row of the in-memory projection state.

    For open tasks: ``status="open"``, ``resolved_at=None``.
    For completed/cancelled tasks lingering inside the TTL window:
    ``status="completed"`` or ``"cancelled"``, ``resolved_at`` set.

    Carrying status + resolved_at alongside the rendered line lets
    the handler distinguish open vs resolved entries without parsing
    the line back out, and lets the TTL sweep walk by resolved_at
    cheaply.
    """

    line: str
    status: str  # "open" | "completed" | "cancelled"
    resolved_at: date | None


_REEVALUATE_EVENTS = frozenset(
    {
        "lithos.task.created",
        "lithos.task.updated",  # forward-compat; source doesn't emit today
        "lithos.task.claimed",
        "lithos.task.released",
    }
)
"""Events that should trigger an actionability re-evaluation.

For all of these the handler reads the current task state and either
adds the task to the projection (if actionable now) or removes it (if
no longer actionable). Claim transitions are the load-bearing case
under D6: a task that was hidden because it was claimable-by-autonomous
appears once a human_blocking route claims it (lithos.task.claimed); a
task in the projection because of a human_blocking claim disappears
when that claim is released and no replacement claim arrives
(lithos.task.released).
"""

_REMOVAL_EVENTS = frozenset({"lithos.task.completed", "lithos.task.cancelled"})
"""Terminal events that always remove the line, regardless of actionability."""

_FILE_HEADER = (
    "%% Auto-generated by lithos-loom (US7+). Hand edits will be "
    "overwritten on the next event. Use Obsidian capture macros for "
    "new tasks (Slice 3+). %%"
)

_PRIORITY_EMOJI: dict[str, str] = {
    "highest": "🔺",
    "high": "⏫",
    "medium": "🔼",
    "low": "🔽",
    "lowest": "⏬",
}
"""D18 enum (`docs/prd/integration.md:102`) → Tasks-plugin emoji.

Strict case-sensitive match: the Lithos surface owns this enum, and
lenient matching would let drift go silent and complicate the
reverse-sync (Slice 2 US21 needs the round-trip to be lossless).
"""


def make_handler(
    cfg: LoomConfig,
    *,
    today_provider: Callable[[], date] = date.today,
) -> Any:
    """Build a stateful obsidian-projection handler bound to ``cfg``.

    The returned coroutine closes over a per-call state dict and the
    target ``tasks_file`` path. Each invocation of ``make_handler``
    produces a fresh handler with its own state — safe to wire
    multiple subscriptions in the same child if ever needed.

    ``cfg.obsidian_sync`` must be set; the obsidian-sync child's spawn
    gate guarantees this, but we assert for defensive readability.

    ``today_provider`` is a seam for testing — production callers leave
    it at the default and get :func:`date.today`. Read at event-handle
    time (not at handler-build time), so a long-running daemon picks up
    each new day naturally on the next event for any task.
    """
    obs = cfg.obsidian_sync
    if obs is None:
        raise RuntimeError(
            "make_handler called without [obsidian_sync] config; the "
            "supervisor's spawn gate should have prevented this"
        )

    tasks_path = obs.vault_path / obs.tasks_file
    state: dict[str, _StateEntry] = {}

    async def handle(event: Event, ctx: Any) -> None:
        # Branch on event type FIRST so an unknown event can't blow up
        # on payload parsing (Copilot review on #17: a missing "id" in
        # a foreign payload would raise KeyError before the unknown-type
        # branch was even reached).
        if event.type not in _REEVALUATE_EVENTS and event.type not in _REMOVAL_EVENTS:
            ctx.logger.debug(
                "obsidian-projection: ignoring unexpected event type %s",
                event.type,
            )
            return

        try:
            task = _task_from_payload(event.payload)
        except (KeyError, TypeError, ValueError) as exc:
            ctx.logger.warning(
                "obsidian-projection: malformed payload for %s: %r", event.type, exc
            )
            return

        # TTL sweep runs at the top of every event handle. Cheap dict
        # walk; long-quiet daemons get a single sweep-driven file
        # rewrite on the next event arrival (US13).
        today_val = today_provider()
        evicted = _evict_expired(state, today_val, obs.resolved_ttl_days)

        prior = state.get(task.id)

        if event.type in _REMOVAL_EVENTS:
            # Promote to resolved — but only for tasks that would have
            # been actionable while open. Autonomous-route work that
            # was never on the operator's view should not suddenly
            # appear in "done this week" queries on completion
            # (PR #21 review: terminal events must respect D6 the same
            # way live re-eval does).
            if not would_be_actionable(task, cfg.routes, obs):
                ctx.logger.debug(
                    "obsidian-projection: skipping terminal event %s for "
                    "never-actionable task %s",
                    event.type,
                    task.id,
                )
                # Defensive: if the task somehow had a stale entry from
                # a config change, drop it now.
                state.pop(task.id, None)
            else:
                new_status = (
                    "completed" if event.type.endswith("completed") else "cancelled"
                )
                # Prefer Lithos's canonical completed_at; fall back to
                # the bus event's receive-at time only when the payload
                # didn't carry one (e.g. a pre-`completed_at`-aware
                # source). PR #21 review issue 3: receive-at drifts vs
                # canonical date around reconnect/replay/tz boundaries.
                resolved_at = _resolved_at_for(event, task)
                state[task.id] = _StateEntry(
                    line=_render_resolved_line(task, new_status, resolved_at),
                    status=new_status,
                    resolved_at=resolved_at,
                )
        elif prior is not None and prior.status != "open":
            # Resolved entry — terminal status is final. Stale
            # claimed/released/updated events for the same task no-op;
            # only TTL expiry can evict.
            ctx.logger.debug(
                "obsidian-projection: ignoring %s for already-resolved task %s",
                event.type,
                task.id,
            )
        else:
            # Open / unknown — re-evaluate actionability (US11 shape).
            if is_human_actionable(task, cfg.routes, obs):
                state[task.id] = _StateEntry(
                    line=_render_line(task, cfg.routes, today_val),
                    status="open",
                    resolved_at=None,
                )
            else:
                state.pop(task.id, None)

        current = state.get(task.id)
        if current == prior and not evicted:
            # Nothing actionable moved AND no TTL eviction touched the
            # file — skip the write. Saves disk I/O and keeps the
            # file's mtime stable so Obsidian Sync doesn't ripple no-op
            # edits to other devices.
            return

        ctx.logger.debug(
            "obsidian-projection: write triggered by %s for %s (evicted=%d)",
            event.type,
            task.id,
            len(evicted),
        )
        await _write_tasks_file_atomic(tasks_path, _render_file(state))

    return handle


# ── helpers ────────────────────────────────────────────────────────────


def _task_from_payload(payload: Any) -> Task:
    """Reconstruct a :class:`Task` from the SSE source's published payload.

    The :class:`~lithos_loom.sources.lithos_event_stream.LithosEventStream`
    publishes the full Task shape (id, title, status, tags, metadata,
    claims, completed_at), so this is just dict-lookups, not a re-fetch.
    """
    return Task(
        id=str(payload["id"]),
        title=str(payload.get("title", "")),
        status=str(payload.get("status", "")),
        tags=tuple(payload.get("tags") or ()),
        metadata=dict(payload.get("metadata") or {}),
        claims=tuple(payload.get("claims") or ()),
        completed_at=_parse_completed_at(payload.get("completed_at")),
    )


def _parse_completed_at(value: Any) -> datetime | None:
    """Defensive ISO-8601 parse for ``completed_at`` from the SSE payload.

    Returns ``None`` for missing / malformed values so the handler can
    fall back to ``event.timestamp`` rather than crashing.
    """
    if value is None or value == "":
        return None
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        logger.warning(
            "obsidian-projection: ignoring malformed completed_at=%r in payload",
            value,
        )
        return None


def _render_line(
    task: Task,
    routes: Sequence[RouteConfig],
    today: date,
) -> str:
    """Render one Tasks-plugin task line for an open task.

    Field order (omit optional markers when they don't apply):

        - [ ] <title> [<prio>] 🆔 lithos:<id> [⛔ lithos:<dep>]... \
            [📅 <date>] [#project/<slug>] [#lithos/<route>]

    Titles with embedded newlines (rare in Lithos but possible) are
    collapsed to spaces so the markdown line stays single-line. The
    ``🆔 lithos:<id>`` marker is what lets US14's dedup identify the
    same task across rewrites.

    US13 keeps completed/cancelled lines around for
    ``resolved_ttl_days`` (see :func:`_render_resolved_line`).
    """
    title = " ".join(task.title.split())  # collapse \n, \r, runs of spaces
    parts: list[str] = [f"- [ ] {title}"]

    priority = _priority_marker(task)
    if priority is not None:
        parts.append(priority)

    parts.append(f"🆔 lithos:{task.id}")

    parts.extend(_dep_markers(task))

    due = _due_date_str(task, routes, today)
    if due is not None:
        parts.append(f"📅 {due}")

    project = task.metadata.get("project")
    if isinstance(project, str) and project:
        parts.append(f"#project/{project}")

    route_name = human_blocking_route_name(task, routes)
    if route_name:
        parts.append(f"#lithos/{route_name}")

    return " ".join(parts)


def _render_resolved_line(task: Task, status: str, resolved_at: date) -> str:
    """Render the historical-line shape for completed/cancelled tasks.

    Matches the PRD example exactly (``docs/prd/integration.md:253-255``):

        - [x] <title> ✅ <date> 🆔 lithos:<id> [#project/<slug>]
        - [-] <title> ❌ <date> 🆔 lithos:<id> [#project/<slug>]

    Resolved tasks drop priority / dep / due-date / route-name
    markers — they are historical record, not actionable work. The
    ``#project/<slug>`` tag is kept so the operator's
    ``done-this-week-for-project-X`` queries still cluster correctly.
    """
    checkbox = "[x]" if status == "completed" else "[-]"
    marker_emoji = "✅" if status == "completed" else "❌"
    title = " ".join(task.title.split())
    parts: list[str] = [
        f"- {checkbox} {title}",
        f"{marker_emoji} {resolved_at.isoformat()}",
        f"🆔 lithos:{task.id}",
    ]
    project = task.metadata.get("project")
    if isinstance(project, str) and project:
        parts.append(f"#project/{project}")
    return " ".join(parts)


def _resolved_at_for(event: Event, task: Task) -> date:
    """Pick the canonical resolution date for a terminal event.

    Preference order (per PR #21 review issue 3):

    1. ``task.completed_at`` from the SSE payload — this is Lithos's
       canonical timestamp, written when the task transitioned to a
       terminal state. Stable across reconnect-replay, restart, and
       any future bootstrap-resolved-discovery path.
    2. ``event.timestamp.astimezone().date()`` — the bus event's
       receive-at time. Fallback only; drifts vs. canonical for
       delayed/replayed events but matches the local-tz "today" the
       operator sees.

    Both branches return a local-tz ``date`` so the rendered marker
    matches the operator's calendar.
    """
    if task.completed_at is not None:
        return task.completed_at.astimezone().date()
    return event.timestamp.astimezone().date()


def _evict_expired(
    state: dict[str, _StateEntry],
    today: date,
    ttl_days: int,
) -> list[str]:
    """Drop state entries whose ``resolved_at < today - ttl_days``.

    Open entries (``resolved_at is None``) are never affected.
    Returns the list of evicted task IDs so the caller can decide
    whether the file content moved even when the triggering event
    itself didn't change the keyed entry.

    ``ttl_days`` is validated as ``>= 0`` by the config parser; the
    defensive check below is for direct-callsite robustness.
    """
    if ttl_days < 0:
        return []
    cutoff = today - timedelta(days=ttl_days)
    evicted: list[str] = []
    for tid, entry in list(state.items()):
        if entry.resolved_at is not None and entry.resolved_at < cutoff:
            del state[tid]
            evicted.append(tid)
    return evicted


def _priority_marker(task: Task) -> str | None:
    """Map ``task.metadata.priority`` (D18 enum) to its Tasks-plugin emoji.

    Returns ``None`` for absent / non-string / unknown-enum values so
    the renderer simply omits the marker. Unknown values are warn-
    logged once per event — same shape as :func:`_parse_scheduled_for`,
    because malformed metadata must never crash the projection.
    """
    value = task.metadata.get("priority")
    if value is None:
        return None
    if not isinstance(value, str):
        logger.warning(
            "obsidian-projection: ignoring non-string metadata.priority=%r",
            value,
        )
        return None
    emoji = _PRIORITY_EMOJI.get(value)
    if emoji is None:
        logger.warning(
            "obsidian-projection: ignoring unknown metadata.priority=%r "
            "(expected one of: %s)",
            value,
            ", ".join(_PRIORITY_EMOJI),
        )
    return emoji


def _dep_markers(task: Task) -> list[str]:
    """Render one ``⛔ lithos:<dep_id>`` marker per entry in
    ``task.metadata.depends_on`` (D19).

    Preserves list order; dedups duplicate IDs (first occurrence
    wins) since the marker is a visual signal not a count. Returns
    ``[]`` for absent / ``None`` / non-list / all-invalid inputs.
    Non-string and empty-string entries are skipped with a single
    warn per event — same shape as :func:`_priority_marker` and
    :func:`_parse_scheduled_for`, so malformed metadata can never
    crash the subscription loop.
    """
    raw = task.metadata.get("depends_on")
    if raw is None:
        return []
    if not isinstance(raw, list):
        logger.warning(
            "obsidian-projection: ignoring non-list metadata.depends_on=%r",
            raw,
        )
        return []

    seen: set[str] = set()
    markers: list[str] = []
    bad: list[Any] = []
    for entry in raw:
        if not isinstance(entry, str) or not entry:
            bad.append(entry)
            continue
        if entry in seen:
            continue
        seen.add(entry)
        markers.append(f"⛔ lithos:{entry}")
    if bad:
        logger.warning(
            "obsidian-projection: skipping invalid entries in metadata.depends_on=%r",
            bad,
        )
    return markers


def _due_date_str(
    task: Task,
    routes: Sequence[RouteConfig],
    today: date,
) -> str | None:
    """D10 due-date semantics.

    Hybrid policy from ``docs/prd/integration.md`` D10:

    - ``task.metadata.scheduled_for`` (if present and parseable) is an
      explicit override and wins for all cases.
    - Else, tasks claimed by a ``human_blocking = true`` route render
      ``today`` so they surface in the operator's daily query.
    - Else (orphan / backlog), no ``📅`` marker is emitted; the user's
      Inbox query (open tasks without due/scheduled/start date) picks
      them up naturally.
    """
    override = _parse_scheduled_for(task.metadata.get("scheduled_for"))
    if override is not None:
        return override.isoformat()
    if human_blocking_route_name(task, routes) is not None:
        return today.isoformat()
    return None


def _parse_scheduled_for(value: Any) -> date | None:
    """Best-effort parse of ``metadata.scheduled_for``.

    Accepts ``YYYY-MM-DD`` and full ISO 8601 datetime strings; returns
    ``None`` for anything we can't read. Malformed metadata must never
    crash the projection — a warn-and-fall-through is the right shape.
    """
    if not isinstance(value, str) or not value:
        return None
    try:
        # Datetime form ('2026-06-15T09:00:00Z' etc.). fromisoformat
        # in 3.11+ accepts the trailing 'Z'.
        if "T" in value:
            return datetime.fromisoformat(value).date()
        return date.fromisoformat(value)
    except ValueError:
        logger.warning(
            "obsidian-projection: ignoring malformed metadata.scheduled_for=%r",
            value,
        )
        return None


def _render_file(state: dict[str, _StateEntry]) -> str:
    """Render the full file content from the state dict.

    Open and resolved entries are interleaved when sorted by task
    id; the user's existing Tasks-plugin queries differentiate via
    the checkbox state (``[ ]`` vs ``[x]``/``[-]``).

    Sorted by task id for deterministic output (cheap stability for
    tests and for content-hash dedup once US14 lands).
    """
    if not state:
        return _FILE_HEADER + "\n"
    lines = [_FILE_HEADER, ""]
    for tid in sorted(state):
        lines.append(state[tid].line)
    lines.append("")
    return "\n".join(lines)


async def _write_tasks_file_atomic(path: Path, content: str) -> None:
    """Atomically rewrite ``path`` with ``content``.

    Strategy: write to ``<path>.tmp``, fsync, then ``os.replace`` onto
    the final path. ``os.replace`` is atomic on POSIX. Creates
    ``path.parent`` if absent. If anything between the temp-write and
    the replace raises, the temp file is best-effort cleaned up so a
    failed write doesn't litter the vault with ``tasks.md.tmp``
    (Copilot review on #17, mirroring ``write_result_atomically`` in
    plugin_runner.py).

    Synchronous I/O inside an async function — fine for the
    vault-sized files this serves (<10kB typical). Move to
    ``asyncio.to_thread`` if write latency under load becomes an issue.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        fd = os.open(tmp, os.O_RDONLY)
        try:
            os.fsync(fd)
        finally:
            os.close(fd)
        os.replace(tmp, path)
    except Exception:
        # Best-effort cleanup. If unlink itself fails (already gone,
        # permission flip), swallow — the original exception is more
        # informative for the operator.
        with contextlib.suppress(OSError):
            tmp.unlink()
        raise
    # Yield once so the async caller can be cancelled cleanly between
    # events even under back-to-back delivery.
    await asyncio.sleep(0)
