"""``obsidian-projection`` subscription handler (Slice 1 US8).

Turns ``lithos.task.*`` events into a markdown file at
``vault_path / tasks_file`` that the Obsidian Tasks plugin can query.

**Event vocabulary:** the user story names
``{created,updated,completed,cancelled}``, but the live SSE source
(``LithosEventStream``) only emits
``{created,claimed,released,completed,cancelled}`` — there is no
``updated`` event in the Lithos surface today. We subscribe to all
six so the projection actually sees claim transitions (which is what
D6 needs to decide actionability), plus ``updated`` as a forward-
compatibility no-op should the source ever emit it.

Line shape after US13:

    %% Auto-generated by lithos-loom. Hand edits will be overwritten. ... %%

    Open tasks:
        - [ ] <title> [<prio>] 🆔 lithos:<id> [⛔ lithos:<dep>]... \
            [📅 <date>] [#project/<slug>] [#lithos/<route>]

    Resolved tasks (within resolved_ttl_days):
        - [x] <title> ✅ <date> 🆔 lithos:<id> [#project/<slug>]
        - [-] <title> ❌ <date> 🆔 lithos:<id> [#project/<slug>]

(``[⛔ lithos:<dep>]...`` is zero-or-more — one marker per entry
in ``task.metadata.depends_on``.) Optional markers are emitted
only when they apply (see ``_render_line`` and
``_render_resolved_line``). Resolved lines drop actionability-only
markers (priority, deps, due date, ``#lithos/<route>``) — they are
historical record, not work. The base US8 shape —
``- [ ] <title> 🆔 lithos:<id>`` — is preserved for orphan tasks
with no priority / deps / project / scheduled_for / claim, which
is the most common case during early adoption.

US12 ("dependency-blocked tasks still project") is implicitly
satisfied here: ``include_blocked = True`` is the
``ObsidianSyncConfig`` default (US7) and ``is_human_actionable``
only hides blocked tasks when the operator explicitly opts out
(US8) — so by default a task with ``depends_on`` set still appears,
just decorated with ``⛔`` markers the Tasks plugin uses to
recognise it as blocked.

US13 keeps completed/cancelled lines around for
``resolved_ttl_days`` (default 7, on ``ObsidianSyncConfig`` since
US7) so the operator's "done this week" / "cancelled this week"
Tasks-plugin queries work without polluting the open-task inbox.
A TTL sweep runs at the top of every event handle — cheap dict
walk, no new timer infrastructure; long-quiet daemons get a
single sweep-driven file rewrite on the next event arrival.
Resolved entries are immune to re-evaluation events: stale
claimed/released/updated for an already-resolved task no-op on
the state; only TTL expiry can evict.

Terminal events are gated through ``would_be_actionable`` (same
predicate as ``is_human_actionable`` minus the status check) so
autonomous-route work that was never on the operator's view does
not suddenly appear in "done this week" queries on completion.
Resolution dates anchor on Lithos's canonical ``resolved_at``
(falling back to ``event.timestamp`` only if the payload is silent),
so reconnect / replay / restart paths render the same date the
operator would have seen at live receipt.

Restart-recovery: ``LithosEventStream`` accepts
``bootstrap_resolved_window`` (set to ``timedelta(days=resolved_ttl_days)``
by the ``obsidian-sync`` child) and fetches recent completed +
cancelled tasks at bootstrap via Lithos's server-side
``resolved_since`` filter (lithos#286), publishing each as the
appropriate terminal-event type. Open tasks replay as ``created``;
the in-memory state thus rebuilds naturally on restart — same
idempotency contract as ``RouteRunner._processed_tasks`` — for
both open and resolved entries.

The handler maintains an in-process state dict
``{task_id → _StateEntry}``.

File writes are layered (US14):

1. **In-memory short-circuit.** When an event leaves the keyed
   ``_StateEntry`` unchanged and the TTL sweep evicted nothing, the
   write is skipped before rendering — the cheap fast path for
   replayed events.
2. **Debounce / coalesce.** Each event schedules a deferred
   ``_flush()`` task; a subsequent event within the
   ``debounce_seconds`` window cancels-and-reschedules so bursts
   (especially bootstrap) coalesce into a single flush at
   quiescence. ``debounce_seconds = 0`` (test default) disables this
   and runs ``_flush()`` inline. Production passes a small positive
   value from the ``obsidian-sync`` child.
3. **Content-hash dedup.** The flush renders the file string,
   SHA-256s it, and compares to ``last_written_hash`` (seeded from
   the existing on-disk file at handler init via
   ``_hash_existing_file``, then updated after each successful
   write). When they match, the atomic-write dance is skipped — so
   a quiet-KB restart converges to the pre-restart disk content and
   the single coalesced flush is a hash-match, zero writes,
   zero mtime ripples.
4. **Atomic write.** Write to ``<path>.tmp``, fsync, then
   ``os.replace`` onto the final path. The ``.tmp`` file is best-
   effort cleaned up on any failure between write and replace, so a
   crashed mid-write doesn't litter the vault with ``tasks.md.tmp``.

Pending flushes are best-effort under shutdown. When the
subscription task is cancelled mid-debounce, the in-flight flush
task is cancelled too and its writes are dropped. Correctness
self-heals on restart: the bootstrap rebuilds state from Lithos
and the first divergent event writes the corrected content (the
disk-seed catches the no-divergence case for free). No Loom-side
persistence is required.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import logging
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

from lithos_loom.bus import Event
from lithos_loom.config import LoomConfig
from lithos_loom.lithos_client import Task
from lithos_loom.render import (
    due_date_str as _due_date_str,
)
from lithos_loom.render import (
    render_line as _render_line,
)
from lithos_loom.render import (
    render_resolved_line as _render_resolved_line,
)
from lithos_loom.render import (
    validated_priority as _validated_priority,
)
from lithos_loom.subscriptions._atomic_write import write_file_atomic
from lithos_loom.subscriptions._human_actionable import (
    is_human_actionable,
    would_be_actionable,
)
from lithos_loom.sync_state import ProjectionSyncState

__all__ = ["make_handler"]

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class _StateEntry:
    """One row of the in-memory projection state.

    For open tasks: ``status="open"``, ``resolved_at=None``,
    ``priority`` is the validated D18 enum or ``None``, ``due_date``
    is the ``YYYY-MM-DD`` string the renderer would emit in the
    ``📅`` marker or ``None``.
    For completed/cancelled tasks lingering inside the TTL window:
    ``status="completed"`` or ``"cancelled"``, ``resolved_at`` set,
    ``priority`` and ``due_date`` are always ``None`` (the renderer
    drops both markers on resolved lines per the PRD example).

    Carrying status + resolved_at + priority + due_date alongside the
    rendered line lets the handler distinguish open vs resolved
    entries without parsing the line back out, lets the TTL sweep
    walk by resolved_at cheaply, and lets ``_flush`` extract per-task
    priority + due_date for the ``sync_state`` maps without
    re-parsing the rendered line. The ``sync_state`` maps in turn
    feed the fs-watcher's diff for the corresponding
    ``obsidian.task.priority_changed`` / ``obsidian.task.due_date_changed``
    event families.
    """

    line: str
    status: str  # "open" | "completed" | "cancelled"
    resolved_at: date | None
    priority: str | None = None
    due_date: str | None = None


_REEVALUATE_EVENTS = frozenset(
    {
        "lithos.task.created",
        "lithos.task.updated",
        "lithos.task.claimed",
        "lithos.task.released",
    }
)
"""Events that should trigger an actionability re-evaluation.

For all of these the handler reads the current task state and either
adds the task to the projection (if actionable now) or removes it (if
no longer actionable). Claim transitions are the load-bearing case
under D6: a task that was hidden because it was claimable-by-autonomous
appears once a human_blocking route claims it (lithos.task.claimed); a
task in the projection because of a human_blocking claim disappears
when that claim is released and no replacement claim arrives
(lithos.task.released).

``lithos.task.updated`` (lithos#283 / PR #284) carries the post-edit
task snapshot — the source force-refreshes for that event type, so
title / tag / priority changes flow through here within the debounce
window.
"""

_REMOVAL_EVENTS = frozenset({"lithos.task.completed", "lithos.task.cancelled"})
"""Terminal events that always remove the line, regardless of actionability."""

_FILE_HEADER = (
    "%% Auto-generated by lithos-loom (US7+). Hand edits will be "
    "overwritten on the next event. Use Obsidian capture macros for "
    "new tasks (Slice 3+). %%"
)

# ``_PRIORITY_EMOJI`` lives in :mod:`lithos_loom.render` now (extracted
# in Slice 3 so the capture-macro CLI can re-render lines identical to
# what the projection writes). Aliased above as ``_PRIORITY_EMOJI`` so
# existing references in this module keep working.

_STATUS_TO_MARKER: dict[str, str] = {
    "open": "[ ]",
    "completed": "[x]",
    "cancelled": "[-]",
}
"""Map a ``_StateEntry.status`` to the checkbox marker the renderer
emits. Used by ``_flush`` to publish per-task marker state into the
shared :class:`ProjectionSyncState` so the fs watcher (US23) can tell
projection writes from user edits on a per-task basis."""


def make_handler(
    cfg: LoomConfig,
    *,
    today_provider: Callable[[], date] = date.today,
    debounce_seconds: float = 0.0,
    sync_state: ProjectionSyncState | None = None,
) -> Any:
    """Build a stateful obsidian-projection handler bound to ``cfg``.

    The returned coroutine closes over a per-call state dict and the
    target ``tasks_file`` path. Each invocation of ``make_handler``
    produces a fresh handler with its own state — safe to wire
    multiple subscriptions in the same child if ever needed.

    ``cfg.obsidian_sync`` must be set; the obsidian-sync child's spawn
    gate guarantees this, but we assert for defensive readability.

    ``today_provider`` is a seam for testing — production callers leave
    it at the default and get :func:`date.today`. Read at event-handle
    time (not at handler-build time), so a long-running daemon picks up
    each new day naturally on the next event for any task.

    ``debounce_seconds`` controls write coalescing (US14):

    - ``0.0`` (default): each event triggers an inline flush. Tests
      use this so they can assert on the file state immediately after
      ``await handler(...)``.
    - ``> 0``: each event schedules a deferred ``_flush()`` task; a
      subsequent event within the window cancels and reschedules so
      bursts (bootstrap) coalesce into a single write at convergence.
      The ``obsidian-sync`` child sets this to a small positive value
      so multi-task restart on a quiet KB causes zero on-disk changes
      (the convergent flush hash-matches the disk seed and skips).

    Pending flushes are best-effort: shutdown via task cancellation
    drops them, but the restart bootstrap rebuilds state from Lithos
    and the first divergent event writes the corrected content. Lost
    flushes therefore self-heal — no Loom-side persistence required.

    ``sync_state`` is the Slice 2 US23 coordination handle. The handler
    updates ``sync_state.last_written_hash`` and
    ``sync_state.task_status_markers`` *before* committing each atomic
    rename so the
    :class:`~lithos_loom.sources.obsidian_fs_watcher.ObsidianFsWatcher`
    can identify projection-driven file changes as self-writes and
    suppress them. ``None`` (test default) constructs a fresh isolated
    state — the projection still works, just without a watcher
    consumer. Production callers in
    :mod:`lithos_loom.children.obsidian_sync` pass a shared instance.
    """
    obs = cfg.obsidian_sync
    if obs is None:
        raise RuntimeError(
            "make_handler called without [obsidian_sync] config; the "
            "supervisor's spawn gate should have prevented this"
        )

    tasks_path = obs.vault_path / obs.tasks_file
    state: dict[str, _StateEntry] = {}
    sync_state = sync_state if sync_state is not None else ProjectionSyncState()
    # Content-hash dedup (US14). Seeded from disk so the convergent
    # flush — where the in-memory state lands at the same content as
    # what was on disk before the restart — skips the write entirely.
    # With debounce_seconds > 0, multi-event bootstrap coalesces into
    # one flush at quiescence; that single flush is what the disk-seed
    # short-circuits. FileNotFound / OSError → None, first write
    # seeds the hash from new content. Seeded into sync_state only
    # when not already set, so the obsidian-sync child's pre-seeding
    # (if any) wins over the projection's defensive re-read.
    if sync_state.last_written_hash is None:
        sync_state.last_written_hash = _hash_existing_file(tasks_path)
    # Pending debounced flush task (None when not debouncing or when
    # the last burst has already flushed). Subsequent events within
    # the debounce window cancel-and-reschedule this task.
    pending_flush: asyncio.Task[None] | None = None

    async def handle(event: Event, ctx: Any) -> None:
        # Branch on event type FIRST so an unknown event can't blow up
        # on payload parsing (Copilot review on #17: a missing "id" in
        # a foreign payload would raise KeyError before the unknown-type
        # branch was even reached).
        if event.type not in _REEVALUATE_EVENTS and event.type not in _REMOVAL_EVENTS:
            ctx.logger.debug(
                "obsidian-projection: ignoring unexpected event type %s",
                event.type,
            )
            return

        try:
            task = _task_from_payload(event.payload)
        except (KeyError, TypeError, ValueError) as exc:
            ctx.logger.warning(
                "obsidian-projection: malformed payload for %s: %r", event.type, exc
            )
            return

        # TTL sweep runs at the top of every event handle. Cheap dict
        # walk; long-quiet daemons get a single sweep-driven file
        # rewrite on the next event arrival (US13).
        today_val = today_provider()
        evicted = _evict_expired(state, today_val, obs.resolved_ttl_days)

        prior = state.get(task.id)

        if event.type in _REMOVAL_EVENTS:
            # Promote to resolved — but only for tasks that would have
            # been actionable while open. Autonomous-route work that
            # was never on the operator's view should not suddenly
            # appear in "done this week" queries on completion
            # (PR #21 review: terminal events must respect D6 the same
            # way live re-eval does).
            if not would_be_actionable(task, cfg.routes, obs):
                ctx.logger.debug(
                    "obsidian-projection: skipping terminal event %s for "
                    "never-actionable task %s",
                    event.type,
                    task.id,
                )
                # Defensive: if the task somehow had a stale entry from
                # a config change, drop it now.
                state.pop(task.id, None)
            else:
                new_status = (
                    "completed" if event.type.endswith("completed") else "cancelled"
                )
                # Prefer Lithos's canonical resolved_at; fall back to
                # the bus event's receive-at time only when the payload
                # didn't carry one (e.g. a pre-`resolved_at`-aware
                # source). PR #21 review issue 3: receive-at drifts vs
                # canonical date around reconnect/replay/tz boundaries.
                resolved_at = _resolved_at_for(event, task)
                state[task.id] = _StateEntry(
                    line=_render_resolved_line(task, new_status, resolved_at),
                    status=new_status,
                    resolved_at=resolved_at,
                )
        elif prior is not None and prior.status != "open":
            # Resolved entry — terminal status is final. Stale
            # claimed/released/updated events for the same task no-op;
            # only TTL expiry can evict.
            ctx.logger.debug(
                "obsidian-projection: ignoring %s for already-resolved task %s",
                event.type,
                task.id,
            )
        else:
            # Open / unknown — re-evaluate actionability (US11 shape).
            if is_human_actionable(task, cfg.routes, obs):
                state[task.id] = _StateEntry(
                    line=_render_line(task, cfg.routes, today_val),
                    status="open",
                    resolved_at=None,
                    priority=_validated_priority(task),
                    # Reuse the renderer's due_date computation so
                    # the projection's _StateEntry holds exactly
                    # what the renderer puts on the line. The
                    # fs-watcher's _DUE_DATE_RE matches that
                    # string verbatim.
                    due_date=_due_date_str(task, cfg.routes, today_val),
                )
            else:
                state.pop(task.id, None)

        current = state.get(task.id)
        if current == prior and not evicted:
            # Nothing actionable moved AND no TTL eviction touched the
            # file — skip even scheduling a flush. Saves disk I/O and
            # keeps the file's mtime stable so Obsidian Sync doesn't
            # ripple no-op edits to other devices.
            return

        # Schedule a flush. The flush itself runs the hash check
        # (skip when content is byte-identical to the last write or
        # the disk seed); debouncing coalesces bursts so the multi-
        # task bootstrap-convergence case becomes a single hash-
        # skipped flush at quiescence.
        ctx.logger.debug(
            "obsidian-projection: scheduling flush for %s on %s (evicted=%d)",
            task.id,
            event.type,
            len(evicted),
        )
        await _schedule_flush()

    async def _flush() -> None:
        """Render current state, hash, compare, and (maybe) write.

        Skips the atomic-write dance when the rendered content's
        SHA-256 matches ``sync_state.last_written_hash`` (which is
        seeded from disk on init, then updated after each successful
        write).

        **Ordering — write first, sync_state second.** The disk
        commit runs before the ``sync_state`` update; that keeps
        ``sync_state`` from ever being ahead of disk. If the atomic
        write raises, ``sync_state`` is simply never touched, so no
        rollback is needed and ``write_version`` can't drift either
        — the US14 retry on the next event re-renders the same
        content, the hash-skip short-circuit fires correctly, and
        the watcher's self-write suppression keeps seeing consistent
        state.

        This ordering only works because :func:`write_file_atomic`
        has no internal ``await`` points (enforced; see its docstring).
        ``await coro()`` on a yield-less coroutine runs the coroutine
        to completion synchronously, so there is no observable
        interleaving between ``os.replace`` returning and the
        ``record_projection_write`` call below — a watcher poll
        can only happen at a suspension point, and the first one
        after the rename is the trailing ``asyncio.sleep(0)`` *after*
        sync_state has already been updated.

        ``CancelledError`` is intentionally not caught. Cancellation
        cannot fire mid-rename (no yields in the atomic write), and
        if it ever fires at the trailing ``sleep(0)`` the rename and
        sync_state update are both already complete and consistent.
        """
        content = _render_file(state)
        content_hash = hashlib.sha256(content.encode("utf-8")).digest()
        if content_hash == sync_state.last_written_hash:
            logger.debug("obsidian-projection: flush content unchanged; skipping write")
            return
        markers = {tid: _STATUS_TO_MARKER[entry.status] for tid, entry in state.items()}
        # Priority map (Slice 2 US21). Only open entries carry a
        # priority; resolved entries always map to ``None`` because
        # the renderer drops the priority emoji on the resolved-line
        # shape — surfacing them here would let the watcher diff
        # against a stale projection-known priority after a task
        # resolves.
        priority_markers = {
            tid: (entry.priority if entry.status == "open" else None)
            for tid, entry in state.items()
        }
        # Due-date map (Slice 3 round-trip). Same shape as the
        # priority map: open entries carry the rendered date string
        # (or ``None``); resolved entries always map to ``None``
        # because the renderer drops the 📅 marker on resolved
        # lines.
        due_date_markers = {
            tid: (entry.due_date if entry.status == "open" else None)
            for tid, entry in state.items()
        }
        # Disk first. Raises → sync_state untouched → next event retries.
        await write_file_atomic(tasks_path, content)
        # Synchronously update sync_state. No yield between the
        # rename returning and this call, so the fs watcher never
        # observes the new file content without the matching
        # coordination state. The ``write_version`` bump inside
        # ``record_projection_write`` only happens here on the
        # success path, so a failed write doesn't trick the watcher
        # into thinking the projection wrote.
        sync_state.record_projection_write(
            content_hash=content_hash,
            task_status_markers=markers,
            task_priority_markers=priority_markers,
            task_due_date_markers=due_date_markers,
        )
        # Cancellation point for clean shutdown between events; safe
        # to fire here because both the rename AND the sync_state
        # update are already complete.
        await asyncio.sleep(0)

    async def _delayed_flush() -> None:
        """Sleep the debounce window, then flush.

        A newer event arriving within the window cancels this task
        (raises ``CancelledError`` inside the sleep); we swallow it
        and return without flushing — the newer event will have
        scheduled its own ``_delayed_flush`` for its own latest
        state, so the flush happens at the burst's tail.
        """
        try:
            await asyncio.sleep(debounce_seconds)
        except asyncio.CancelledError:
            return
        await _flush()

    async def _schedule_flush() -> None:
        """Either flush inline (debounce disabled) or schedule a
        deferred flush task (debounce enabled).

        Test default is ``debounce_seconds = 0`` → inline flush so
        ``await handler(...)`` produces an immediately-observable
        file state. Production sets a small positive value so bursts
        coalesce.
        """
        nonlocal pending_flush
        if debounce_seconds <= 0:
            await _flush()
            return
        if pending_flush is not None and not pending_flush.done():
            pending_flush.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await pending_flush
        pending_flush = asyncio.create_task(_delayed_flush())

    return handle


# ── helpers ────────────────────────────────────────────────────────────


def _task_from_payload(payload: Any) -> Task:
    """Reconstruct a :class:`Task` from the SSE source's published payload.

    The :class:`~lithos_loom.sources.lithos_event_stream.LithosEventStream`
    publishes the full Task shape (id, title, status, tags, metadata,
    claims, resolved_at), so this is just dict-lookups, not a re-fetch.
    """
    return Task(
        id=str(payload["id"]),
        title=str(payload.get("title", "")),
        status=str(payload.get("status", "")),
        tags=tuple(payload.get("tags") or ()),
        metadata=dict(payload.get("metadata") or {}),
        claims=tuple(payload.get("claims") or ()),
        resolved_at=_parse_resolved_at(payload.get("resolved_at")),
    )


def _parse_resolved_at(value: Any) -> datetime | None:
    """Defensive ISO-8601 parse for ``resolved_at`` from the SSE payload.

    Returns ``None`` for missing / malformed values so the handler can
    fall back to ``event.timestamp`` rather than crashing.
    """
    if value is None or value == "":
        return None
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        logger.warning(
            "obsidian-projection: ignoring malformed resolved_at=%r in payload",
            value,
        )
        return None


def _resolved_at_for(event: Event, task: Task) -> date:
    """Pick the canonical resolution date for a terminal event.

    Preference order (per PR #21 review issue 3):

    1. ``task.resolved_at`` from the SSE payload — this is Lithos's
       canonical timestamp (lithos#286 / PR #288), written by both
       ``complete_task`` and ``cancel_task`` when the task transitions
       to a terminal state. Stable across reconnect-replay, restart,
       and the bootstrap-resolved-discovery path.
    2. ``event.timestamp.astimezone().date()`` — the bus event's
       receive-at time. Fallback only; drifts vs. canonical for
       delayed/replayed events but matches the local-tz "today" the
       operator sees.

    Both branches return a local-tz ``date`` so the rendered marker
    matches the operator's calendar.
    """
    if task.resolved_at is not None:
        return task.resolved_at.astimezone().date()
    return event.timestamp.astimezone().date()


def _evict_expired(
    state: dict[str, _StateEntry],
    today: date,
    ttl_days: int,
) -> list[str]:
    """Drop state entries whose ``resolved_at < today - ttl_days``.

    Open entries (``resolved_at is None``) are never affected.
    Returns the list of evicted task IDs so the caller can decide
    whether the file content moved even when the triggering event
    itself didn't change the keyed entry.

    ``ttl_days`` is validated as ``>= 0`` by the config parser; the
    defensive check below is for direct-callsite robustness.
    """
    if ttl_days < 0:
        return []
    cutoff = today - timedelta(days=ttl_days)
    evicted: list[str] = []
    for tid, entry in list(state.items()):
        if entry.resolved_at is not None and entry.resolved_at < cutoff:
            del state[tid]
            evicted.append(tid)
    return evicted


def _render_file(state: dict[str, _StateEntry]) -> str:
    """Render the full file content from the state dict.

    Open and resolved entries are interleaved when sorted by task
    id; the user's existing Tasks-plugin queries differentiate via
    the checkbox state (``[ ]`` vs ``[x]``/``[-]``).

    Sorted by task id for deterministic output (cheap stability for
    tests and for US14's content-hash dedup at the file boundary).
    """
    if not state:
        return _FILE_HEADER + "\n"
    lines = [_FILE_HEADER, ""]
    for tid in sorted(state):
        lines.append(state[tid].line)
    lines.append("")
    return "\n".join(lines)


def _hash_existing_file(path: Path) -> bytes | None:
    """Compute the SHA-256 digest of ``path``'s current contents.

    Returns ``None`` when the file doesn't exist or isn't readable
    (cold start, permission flip, weird filesystem state). Used by
    ``make_handler`` to seed ``last_written_hash`` so a daemon
    restart that rebuilds in-memory state to the same content as the
    on-disk file results in zero disk writes at the convergent point
    (US14).
    """
    try:
        raw = path.read_bytes()
    except (FileNotFoundError, OSError):
        return None
    return hashlib.sha256(raw).digest()


# write_file_atomic moved to ``._atomic_write`` so Slice 4's
# project-context projection can share the same temp + fsync + rename
# contract — see :mod:`lithos_loom.subscriptions._atomic_write` for
# the load-bearing invariants this projection's _flush relies on.
