"""``obsidian-projection`` subscription handler (Slice 1 US8).

Turns ``lithos.task.*`` events into a markdown file at
``vault_path / tasks_file`` that the Obsidian Tasks plugin can query.

**Event vocabulary:** the user story names
``{created,updated,completed,cancelled}``, but the live SSE source
(``LithosEventStream``) only emits
``{created,claimed,released,completed,cancelled}`` — there is no
``updated`` event in the Lithos surface today. We subscribe to all
six so the projection actually sees claim transitions (which is what
D6 needs to decide actionability), plus ``updated`` as a forward-
compatibility no-op should the source ever emit it.

Line shape after US10:

    %% Auto-generated by lithos-loom. Hand edits will be overwritten. ... %%

    - [ ] <title> [<prio>] 🆔 lithos:<id> [📅 <date>] \
        [#project/<slug>] [#lithos/<route>]

Optional markers are emitted only when they apply (see
``_render_line``). The base US8 shape — ``- [ ] <title> 🆔 lithos:<id>``
— is preserved for orphan tasks with no priority / project /
scheduled_for / claim, which is the most common case during early
adoption.

US11 will add ``⛔ lithos:<dep_id>`` markers (slotted after ``🆔``);
US13 will keep completed/cancelled lines around for
``resolved_ttl_days`` with ``✅``/``❌`` markers. For US8–US10 the
file holds only currently-actionable tasks; completed/cancelled
events remove the line.

The handler maintains an in-process state dict ``{task_id → line}``.
The SSE source's bootstrap replays all open tasks as ``created``
events on daemon startup, so state rebuilds naturally on restart —
same idempotency contract as ``RouteRunner._processed_tasks``.

File writes are atomic: write to ``<path>.tmp``, fsync, then
``os.replace`` onto the final path. The .tmp file is cleaned up on
any failure between write and replace so stale temps don't litter
the vault. Content-hash dedup ("only write when content has actually
changed") is US14; meanwhile this handler skips the write entirely
whenever nothing about the in-memory state changed.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import os
from collections.abc import Callable, Sequence
from datetime import date, datetime
from pathlib import Path
from typing import Any

from lithos_loom.bus import Event
from lithos_loom.config import LoomConfig, RouteConfig
from lithos_loom.lithos_client import Task
from lithos_loom.subscriptions._human_actionable import (
    human_blocking_route_name,
    is_human_actionable,
)

__all__ = ["make_handler"]

logger = logging.getLogger(__name__)

_REEVALUATE_EVENTS = frozenset(
    {
        "lithos.task.created",
        "lithos.task.updated",  # forward-compat; source doesn't emit today
        "lithos.task.claimed",
        "lithos.task.released",
    }
)
"""Events that should trigger an actionability re-evaluation.

For all of these the handler reads the current task state and either
adds the task to the projection (if actionable now) or removes it (if
no longer actionable). Claim transitions are the load-bearing case
under D6: a task that was hidden because it was claimable-by-autonomous
appears once a human_blocking route claims it (lithos.task.claimed); a
task in the projection because of a human_blocking claim disappears
when that claim is released and no replacement claim arrives
(lithos.task.released).
"""

_REMOVAL_EVENTS = frozenset({"lithos.task.completed", "lithos.task.cancelled"})
"""Terminal events that always remove the line, regardless of actionability."""

_FILE_HEADER = (
    "%% Auto-generated by lithos-loom (US7+). Hand edits will be "
    "overwritten on the next event. Use Obsidian capture macros for "
    "new tasks (Slice 3+). %%"
)

_PRIORITY_EMOJI: dict[str, str] = {
    "highest": "🔺",
    "high": "⏫",
    "medium": "🔼",
    "low": "🔽",
    "lowest": "⏬",
}
"""D18 enum (`docs/prd/integration.md:102`) → Tasks-plugin emoji.

Strict case-sensitive match: the Lithos surface owns this enum, and
lenient matching would let drift go silent and complicate the
reverse-sync (Slice 2 US21 needs the round-trip to be lossless).
"""


def make_handler(
    cfg: LoomConfig,
    *,
    today_provider: Callable[[], date] = date.today,
) -> Any:
    """Build a stateful obsidian-projection handler bound to ``cfg``.

    The returned coroutine closes over a per-call state dict and the
    target ``tasks_file`` path. Each invocation of ``make_handler``
    produces a fresh handler with its own state — safe to wire
    multiple subscriptions in the same child if ever needed.

    ``cfg.obsidian_sync`` must be set; the obsidian-sync child's spawn
    gate guarantees this, but we assert for defensive readability.

    ``today_provider`` is a seam for testing — production callers leave
    it at the default and get :func:`date.today`. Read at event-handle
    time (not at handler-build time), so a long-running daemon picks up
    each new day naturally on the next event for any task.
    """
    obs = cfg.obsidian_sync
    if obs is None:
        raise RuntimeError(
            "make_handler called without [obsidian_sync] config; the "
            "supervisor's spawn gate should have prevented this"
        )

    tasks_path = obs.vault_path / obs.tasks_file
    state: dict[str, str] = {}

    async def handle(event: Event, ctx: Any) -> None:
        # Branch on event type FIRST so an unknown event can't blow up
        # on payload parsing (Copilot review on #17: a missing "id" in
        # a foreign payload would raise KeyError before the unknown-type
        # branch was even reached).
        if event.type not in _REEVALUATE_EVENTS and event.type not in _REMOVAL_EVENTS:
            ctx.logger.debug(
                "obsidian-projection: ignoring unexpected event type %s",
                event.type,
            )
            return

        try:
            task = _task_from_payload(event.payload)
        except (KeyError, TypeError, ValueError) as exc:
            ctx.logger.warning(
                "obsidian-projection: malformed payload for %s: %r", event.type, exc
            )
            return

        prior_line = state.get(task.id)

        if event.type in _REMOVAL_EVENTS:
            # Terminal: always remove (US13 will overlay TTL lingering).
            state.pop(task.id, None)
        else:
            # All non-terminal events re-evaluate against current state.
            # claimed/released drive D6's claim-state filter; created
            # covers cold-start; updated is forward-compat.
            if is_human_actionable(task, cfg.routes, obs):
                state[task.id] = _render_line(task, cfg.routes, today_provider())
            else:
                state.pop(task.id, None)

        current_line = state.get(task.id)
        if current_line == prior_line:
            # Nothing actionable moved — skip the write entirely. Covers
            # both "removal of an entry we never had" and "upsert that
            # produces an identical rendered line." Saves disk I/O and
            # keeps the file's mtime stable so Obsidian Sync doesn't
            # ripple no-op edits to other devices.
            return

        ctx.logger.debug(
            "obsidian-projection: %s for %s on %s",
            "upserted" if current_line is not None else "removed",
            task.id,
            event.type,
        )
        await _write_tasks_file_atomic(tasks_path, _render_file(state))

    return handle


# ── helpers ────────────────────────────────────────────────────────────


def _task_from_payload(payload: Any) -> Task:
    """Reconstruct a :class:`Task` from the SSE source's published payload.

    The :class:`~lithos_loom.sources.lithos_event_stream.LithosEventStream`
    publishes the full Task shape (id, title, status, tags, metadata,
    claims), so this is just dict-lookups, not a re-fetch.
    """
    return Task(
        id=str(payload["id"]),
        title=str(payload.get("title", "")),
        status=str(payload.get("status", "")),
        tags=tuple(payload.get("tags") or ()),
        metadata=dict(payload.get("metadata") or {}),
        claims=tuple(payload.get("claims") or ()),
    )


def _render_line(
    task: Task,
    routes: Sequence[RouteConfig],
    today: date,
) -> str:
    """Render one Tasks-plugin task line for an open task.

    Field order (omit optional markers when they don't apply):

        - [ ] <title> [<prio>] 🆔 lithos:<id> [📅 <date>] \
            [#project/<slug>] [#lithos/<route>]

    Titles with embedded newlines (rare in Lithos but possible) are
    collapsed to spaces so the markdown line stays single-line. The
    ``🆔 lithos:<id>`` marker is what lets US14's dedup and future
    enrichment stories identify the same task across rewrites.

    US11 will slot ``⛔ lithos:<dep_id>`` markers after ``🆔``; its
    absence here keeps the line stable across the remaining
    enrichment stories.
    """
    title = " ".join(task.title.split())  # collapse \n, \r, runs of spaces
    parts: list[str] = [f"- [ ] {title}"]

    priority = _priority_marker(task)
    if priority is not None:
        parts.append(priority)

    parts.append(f"🆔 lithos:{task.id}")

    due = _due_date_str(task, routes, today)
    if due is not None:
        parts.append(f"📅 {due}")

    project = task.metadata.get("project")
    if isinstance(project, str) and project:
        parts.append(f"#project/{project}")

    route_name = human_blocking_route_name(task, routes)
    if route_name:
        parts.append(f"#lithos/{route_name}")

    return " ".join(parts)


def _priority_marker(task: Task) -> str | None:
    """Map ``task.metadata.priority`` (D18 enum) to its Tasks-plugin emoji.

    Returns ``None`` for absent / non-string / unknown-enum values so
    the renderer simply omits the marker. Unknown values are warn-
    logged once per event — same shape as :func:`_parse_scheduled_for`,
    because malformed metadata must never crash the projection.
    """
    value = task.metadata.get("priority")
    if value is None:
        return None
    if not isinstance(value, str):
        logger.warning(
            "obsidian-projection: ignoring non-string metadata.priority=%r",
            value,
        )
        return None
    emoji = _PRIORITY_EMOJI.get(value)
    if emoji is None:
        logger.warning(
            "obsidian-projection: ignoring unknown metadata.priority=%r "
            "(expected one of: %s)",
            value,
            ", ".join(_PRIORITY_EMOJI),
        )
    return emoji


def _due_date_str(
    task: Task,
    routes: Sequence[RouteConfig],
    today: date,
) -> str | None:
    """D10 due-date semantics.

    Hybrid policy from ``docs/prd/integration.md`` D10:

    - ``task.metadata.scheduled_for`` (if present and parseable) is an
      explicit override and wins for all cases.
    - Else, tasks claimed by a ``human_blocking = true`` route render
      ``today`` so they surface in the operator's daily query.
    - Else (orphan / backlog), no ``📅`` marker is emitted; the user's
      Inbox query (open tasks without due/scheduled/start date) picks
      them up naturally.
    """
    override = _parse_scheduled_for(task.metadata.get("scheduled_for"))
    if override is not None:
        return override.isoformat()
    if human_blocking_route_name(task, routes) is not None:
        return today.isoformat()
    return None


def _parse_scheduled_for(value: Any) -> date | None:
    """Best-effort parse of ``metadata.scheduled_for``.

    Accepts ``YYYY-MM-DD`` and full ISO 8601 datetime strings; returns
    ``None`` for anything we can't read. Malformed metadata must never
    crash the projection — a warn-and-fall-through is the right shape.
    """
    if not isinstance(value, str) or not value:
        return None
    try:
        # Datetime form ('2026-06-15T09:00:00Z' etc.). fromisoformat
        # in 3.11+ accepts the trailing 'Z'.
        if "T" in value:
            return datetime.fromisoformat(value).date()
        return date.fromisoformat(value)
    except ValueError:
        logger.warning(
            "obsidian-projection: ignoring malformed metadata.scheduled_for=%r",
            value,
        )
        return None


def _render_file(state: dict[str, str]) -> str:
    """Render the full file content from the state dict.

    Sorted by task id for deterministic output (cheap stability for
    tests and for content-hash dedup once US14 lands).
    """
    if not state:
        return _FILE_HEADER + "\n"
    lines = [_FILE_HEADER, ""]
    for tid in sorted(state):
        lines.append(state[tid])
    lines.append("")
    return "\n".join(lines)


async def _write_tasks_file_atomic(path: Path, content: str) -> None:
    """Atomically rewrite ``path`` with ``content``.

    Strategy: write to ``<path>.tmp``, fsync, then ``os.replace`` onto
    the final path. ``os.replace`` is atomic on POSIX. Creates
    ``path.parent`` if absent. If anything between the temp-write and
    the replace raises, the temp file is best-effort cleaned up so a
    failed write doesn't litter the vault with ``tasks.md.tmp``
    (Copilot review on #17, mirroring ``write_result_atomically`` in
    plugin_runner.py).

    Synchronous I/O inside an async function — fine for the
    vault-sized files this serves (<10kB typical). Move to
    ``asyncio.to_thread`` if write latency under load becomes an issue.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        fd = os.open(tmp, os.O_RDONLY)
        try:
            os.fsync(fd)
        finally:
            os.close(fd)
        os.replace(tmp, path)
    except Exception:
        # Best-effort cleanup. If unlink itself fails (already gone,
        # permission flip), swallow — the original exception is more
        # informative for the operator.
        with contextlib.suppress(OSError):
            tmp.unlink()
        raise
    # Yield once so the async caller can be cancelled cleanly between
    # events even under back-to-back delivery.
    await asyncio.sleep(0)
